# Site settings
title: Tales of time
email: ridwan.arefin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog.
baseurl: "/testblog/" # the subpath of your site, e.g. /blog/
url: "http://kaziridwan.github.io" # the base hostname & protocol for your site
twitter_username: ridwanshere
github_username:  kaziridwan

# Build settings
markdown: kramdown

paginate: 10

# markdown: rdiscount
permalink: pretty
pygments: true
